### ISSUE TITLE
Mod allegedly breaks with HypixelModApi forge mod in use by other mods

### ISSUE THREAD

**Issue by IndigoPolecat** [Desco1/WaterSolver#5]
Hello, I am the developer of Bingo Brewers and I have been receiving complaints that your mod stops working when in use with my mod. I assume this is related to my recent switch to use the Hypixel Mod API forge mod as a dependency for my mod, and your recent switch to directly implement the code into your mod. I wanted to bring this issue to your attention so you can hopefully resolve the conflict, which I believe stems from the difference in versions (0.5 vs 1.0) used.

I would recommend trying to implement the Mod API using the 3rd party mod as a dependency, I suspect this would resolve issues.

**Comment by Desco1** [comment]
Fixed on [v1.1.2](https://github.com/Desco1/WaterSolver/releases/tag/v1.1.2) i sure do hope
